70 even handler to search button
cse110-fa21-group2/cse110-fa21-group2 pull request #91
Opened 2021-11-22 06:36 UTC by Hay-Harry

## Details 
Linked the search button and input box with event handler in main. Fetching from API with query and save to local storage. 
Not implemented:
populate search result cards (not sure if Misha has already done it? Will check his pr)
navigate to search results page (router?)

## New Changes
- add event handler to search button to fetch recipes for query 
- add fetched recipes to local Storage (store Recipe to local with query as category name)
- add name "Search recipes input" to landing.html for getting input

## Linked Issue
Include issue number here
#70

## Checklist
- [ ] I have requested 2+ code reviewers
- [ ] I have reviewed and commented my own code.
- [ ] My code follows the style guidelines of this project.
- [ ] I have added new tests as necessary.
- [ ] All new and existing tests pass successfully.

2021-11-22 06:41 UTC, Hay-Harry commented
For API helpers: Only add keyword export, no changes. 
Will use New version API helpers once treeebooor finishes.

2021-11-24 07:31 UTC, RainbowPangolin requested changes
Code needs to be better commented first, and I will add Robert to this so he can see that apiHelpers.js is broken in the main branch. Other than that, good start

2021-11-24 07:31 UTC, RainbowPangolin commented on source/js/apiHelpers.js
> -/**
We need Robert to look at this change, as I have no idea how two versions of the same function snuck its way into the main branch and didn't give him any errors on his machine.

2021-11-24 07:31 UTC, RainbowPangolin commented on source/js/main.js
> + * 3.
Please update the comments to be complete. The trailing '3.' concerns me, as that signals to me that you've missed something. 

Further, put a TODO for anything that needs to be done in the future.

2021-11-24 07:31 UTC, RainbowPangolin commented on source/js/main.js
> +  // console.log(searchResult);
Remove commented out console logs.

2021-11-25 03:34 UTC, RainbowPangolin commented on source/js/apiHelpers.js
> -/**
Resolved in #102

2021-11-25 03:35 UTC, RainbowPangolin commented
Summary of changes requested:

1. Clean up comments
2. Use the new version of apiHelpers.js

2021-11-27 03:35 UTC, Hay-Harry commented
Going update(merge) main to my branch, I will submit a new pr.

2021-11-27 03:35 UTC, closed without merging